创建基础tensor

In [1]:
import torch
a = torch.tensor([2,3,4])
print(a)

tensor([2, 3, 4])


全0/全1

In [6]:
b = torch.zeros(3,1)
c = torch.ones(1,3)
print(b)
print(c)

tensor([[0.],
        [0.],
        [0.]])
tensor([[1., 1., 1.]])
