# 基础tensor
## 一、创建tensor
torch.arang 用于生成一个指定范围内的张量，其元素是按一定步长排列的。

In [ ]:
import torch
a = torch.tensor([2,3,4])
a1 = torch.arange(6)
a2 = torch.arange(start = 0,end = 10,step=2)#左开右闭
print(a)
print(a1)
print(a2)

tensor([2, 3, 4])
tensor([0, 1, 2, 3, 4, 5])
tensor([0, 2, 4, 6, 8])


### 全0/全1

In [6]:
b = torch.zeros(3,1)
c = torch.ones(1,3)
print(b)
print(c)

tensor([[0.],
        [0.],
        [0.]])
tensor([[1., 1., 1.]])


### 随机数（重要！）
randn 正态分布
rand 0-1均匀分布

In [ ]:
d = torch.randn(2,5,5)
e = torch.rand(2,5)

# 3. 开启梯度追踪 (用于神经网络训练)
w = torch.randn(3, 3, requires_grad=True)
print(d)
print(e)

tensor([[[-0.3233, -0.8699, -0.5332, -0.2763, -0.0792],
         [-0.6699,  0.1049,  1.2214,  0.9237, -0.4490],
         [ 0.0898,  1.8888,  0.8689, -0.1160,  0.7914],
         [ 0.1551,  0.2773, -0.8124,  1.6232, -1.5792],
         [-0.1726, -1.8940,  0.6535, -0.6699,  1.8236]],

        [[-1.0977,  0.3996, -0.9025,  0.7284,  0.2097],
         [ 0.0818,  1.0617, -0.1115,  0.1253, -0.8137],
         [-0.5300,  2.5420,  1.8848, -0.6427, -0.2942],
         [ 0.9021,  0.5301,  1.3332,  1.2008,  0.2192],
         [ 1.4211,  0.3284,  0.8930,  0.5487,  0.7990]]])
tensor([[0.3310, 0.0861, 0.0531, 0.2872, 0.4433],
        [0.7788, 0.7973, 0.6356, 0.6832, 0.6688]])


## 二、shape&dtype

shape tensor的形状维度

In [10]:
f = torch.randn(10,8)
print(f.shape)

torch.Size([10, 8])


dtype tensor的数据类型

可以修改tensor的数据类型

In [17]:
f.dtype 
# 修改数据类型
f = f.long()    #torch.int64
f = f.double()  #torch.float64
f= f.float()    #torch.float32
f.dtype

torch.float32

## 三、基本运算

In [ ]:
g = torch.tensor([1,2,3])
h = torch.tensor([4,5,6])
print(g+h)
print(g*h) #逐个位置相乘 点乘

tensor([5, 7, 9])
tensor([ 4, 10, 18])


### 矩阵乘法！！！
@ 和 matmul

**最后两维相乘** 形状 (m, n, k) @ (m, k, p) -> 结果 (m, n, p)

In [22]:
i = torch.rand(3,4)
j = torch.rand(4,8)
print(i@j)
torch.matmul(i,j)

tensor([[1.6617, 1.2985, 1.9601, 2.1342, 1.1823, 1.7572, 1.6681, 0.7494],
        [1.6045, 1.2435, 1.8229, 1.7298, 1.2685, 1.1493, 1.5387, 0.8417],
        [1.4122, 1.3557, 1.9945, 1.9228, 1.4984, 1.3484, 1.5185, 1.1200]])


tensor([[1.6617, 1.2985, 1.9601, 2.1342, 1.1823, 1.7572, 1.6681, 0.7494],
        [1.6045, 1.2435, 1.8229, 1.7298, 1.2685, 1.1493, 1.5387, 0.8417],
        [1.4122, 1.3557, 1.9945, 1.9228, 1.4984, 1.3484, 1.5185, 1.1200]])

## 四、reshape/view(变形)
**reshape：更安全**

**view：更快（但要求内存连续）**

转置 .t() 操作返回的是一个“非连续”的张量视图

In [ ]:
k = torch.arange(6)
l = k.reshape(3,2)
m = k.view(2,3)
print(l)
print(m)

x = torch.randn(2,3)
y = x.t()   # 转置（内存不连续）
y.view(6)   # ❌ 会报错
#正确写法
y = y.contiguous().view(6)


tensor([[0, 1],
        [2, 3],
        [4, 5]])
tensor([[0, 1, 2],
        [3, 4, 5]])
tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])


RuntimeError: view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Use .reshape(...) instead.

## 五、squeeze / unsqueeze(非常常用！！！！)
squeeze 去掉维度 (只能移除大小为 1 的维度)

unsqueeze 增加维度

In [ ]:
n = torch.randn(1,3,2)
n1 = torch.randn(3,2)
n2 = torch.randn(2,3,2) #无法去除
o = n.squeeze()
print(o)
p = n1.unsqueeze(1) #参数是增加的维度位置 0 就是变成(1,3,2) 1就是变成(3,1,2)以此类推
print(p)
p.shape


tensor([[ 0.9460,  0.7940],
        [ 0.8151,  0.6174],
        [-0.0575,  1.3800]])
tensor([[[ 0.1900,  0.6650]],

        [[ 0.4721,  1.7411]],

        [[-1.7424, -0.2986]]])


torch.Size([3, 1, 2])

## 六、Indexing（切片）
和numpy一样

In [ ]:
q = torch.tensor([[1,2,3],[4,5,6],[7,8,9]])
print(q[0])   #第一行
print(q[:,1]) #第二列
print(q[:,-1])#最后一列


tensor([1, 2, 3])
tensor([2, 5, 8])
tensor([3, 6, 9])


### 高级索引

In [64]:
# 布尔索引
scores = torch.tensor([[0.1, 0.9, 0.2],
                       [0.8, 0.3, 0.4]])

# 找出所有大于 0.5 的元素的位置
mask = scores > 0.5
# mask 是布尔矩阵，直接索引会返回所有满足条件的元素（展平为一维）
high_scores = scores[mask] 
# 结果: tensor([0.9, 0.8])
print(high_scores)

# 花式
x = torch.tensor([[1,2],
                  [3,4]])

idx = torch.tensor([0,1])

print(x[idx, idx])  # [1,4]


tensor([0.9000, 0.8000])
tensor([1, 4])


花式索引实践案例

In [ ]:
# attention_scores: (Batch, Seq_Len)
top_k = 3
values, indices = torch.topk(attention_scores, k=top_k, dim=1)

# indices 形状: (Batch, 3)
# 我们需要构造行索引来配合 indices 进行配对提取
batch_indices = torch.arange(attention_scores.size(0)).unsqueeze(1).expand_as(indices)

# 花式索引：提取每行前3大的具体分数（验证用）或对应的Key/Value
selected_values = attention_scores[batch_indices, indices]
# batch_size 即有多少行/批次
# [[0, 0, 0],
#  [1, 1, 1]]
# indices 即每行topk的列位置
# [1, 3, 4],
# [2, 4, 0]

## NumPy ↔ Torch 转换（重要‼️）

numpy --> tensor

torch.from_numpy()  零拷贝 (Zero-copy)：转换速度极快，不复制数据。

torch.tensor()   数据拷贝 (Copy)：会分配新内存并复制数据，转换速度稍慢（对于大数组）。

tensor --> numpy

xxx.numpy()


In [53]:
import numpy as np
r = np.array([1,2,3])
s1 = torch.from_numpy(r) #共享内存
s2 = torch.tensor(r)
print(s1)
print(s2)
s3 = s2.numpy()
s1[1] = 4
print(r)


tensor([1, 2, 3])
tensor([1, 2, 3])
[1 4 3]


## 广播机制
维度大小相等。

其中一个维度大小为 1。

其中一个张量在该维度上不存在（即维度数较少，自动在前面补 1）。


In [56]:
a1 = torch.tensor([4])
a2 = torch.tensor([1,2,3,5])
a1+a2

tensor([5, 6, 7, 9])